#!/usr/bin/perl -w
use strict;
my $usage = "This program convert the ct file generated by mfold to normal format";
my $file = shift or die $usage;

open IN,"<$file" or die "Couldn't open $file!";

my $line = <IN>;
chomp $line;

my @lines = split(/\s/, $line);

print $lines[0].' '.$lines[$#lines]."\n";

while($line = <IN>) {
	chomp $line;
	if($line =~ /^(\w+)\s+(\w+)\s+(\w+)\s+(\w+)\s+(\w+)\s+\w+$/) {
		print "$1 $2 $3 $4 $5\n";
	}
	else {
		print "$line\n";
	}
}
close IN;