#!/usr/bin/perl -w
use strict;
my $usage = "This program convert the dbn file generated by RNAshapes to normal format";
my $file = shift or die $usage;

open IN,"<$file" or die "Couldn't open $file!";

my $line = <IN>;
print $line;

$line = <IN>;
if($line =~ /\s+([A-Za-z]+)\s+/) {
	print "$1\n";
}
while($line = <IN>) {
	if($line =~ /(\S+)\s+(\S+)\s+/) {
		print "$2\t$1\n";
	}
}

close IN;